[package]
name = "pgpreflight"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "pgpreflight"
path = "src/main.rs"

[dependencies]
pgpreflight-core = { path = "../pgpreflight-core", version = "0.1.0" }
pgpreflight-postgres = { path = "../pgpreflight-postgres", version = "0.1.0" }

[dev-dependencies]
serde_json = { workspace = true }
tokio = { workspace = true, features = ["net", "time"] }
tokio-postgres = { workspace = true }
