[package]
name = "pgpreflight-postgres"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
pgpreflight-core = { path = "../pgpreflight-core", version = "0.1.0" }
sqlparser = "0.62"
thiserror = { workspace = true }
